### ISSUE TITLE
A problem about MAGEMin_EquilibriumPath

### ISSUE THREAD

**Issue by CHNxzr** [ComputationalThermodynamics/MAGEMin#44] opened 2022-09-24 14:01 UTC
Hi, what can I do to debug?

![reply30](https://user-images.githubusercontent.com/114136385/192101914-20f7239d-8689-49b3-9667-ecd25ffcf550.png)
![reply31](https://user-images.githubusercontent.com/114136385/192101920-b811a096-b7ed-45d0-b3a4-d55a7cc12682.png)

**Comment by boriskaus** [comment] 2022-09-25 10:18
that's a question for @kellertobs

**Comment by kellertobs** [comment] 2022-09-26 07:24
I tested the composition and PT-path as in the screen grab provided and can't reproduce the error. In my case the data read routine runs through with no problem. Please make sure you've updated your executable to v.1.2.7. If the error persists, can you please post the exact version of MAGEMin_EquilibriumPath.mlx that gives the error?

**Comment by kellertobs** [comment] 2022-09-26 07:56
Having said that, the same test case brought up another error later when the data is written to CSV files. It's an important fix that I'm going to create a pull request for in MAGEMin_dev. The error occurs when a once stable phase disappears later along the PT path. Some of the data arrays need to be padded with zeros to avoid inconsistent array dimensions when writing the data to CSV. @boriskaus or @NicolasRiel, this fix should be updated in the main distribution directly but does not require an update to the MAGEMin executable. I'll tag you in the pull request once it's ready.

**Comment by kellertobs** [comment] 2022-09-26 08:07
pull request for the fix is ready to be merged

**Comment by CHNxzr** [comment] 2022-09-27 12:39
I'm sure I have updated for the latest version. But the problem still exist. 
![reply32](https://user-images.githubusercontent.com/114136385/192527863-ccba9a95-3a0f-4a5a-bd26-bf5d1abe4047.png)

**Comment by boriskaus** [comment] 2022-09-28 07:57
It works fine on my system as well. Does the default computation work for you (not using your own chemistry)?

**Comment by NicolasRiel** [comment] 2022-09-28 08:09
Could you try again, I now pushed the fix from Tobias on MAGEMin repo. I also tried your composition on my machine (On windows) and it works. Just to double check, which mode do you use here?

**Comment by CHNxzr** [comment] 2022-09-29 09:41
> It works fine on my system as well. Does the default computation work for you (not using your own chemistry)?

Yes!

**Comment by boriskaus** [comment] 2022-09-29 09:43
in that case, can you give us more details on which parameters you exactly changed starting from the default parameters (all changes please).

**Comment by CHNxzr** [comment] 2022-09-29 09:45
> Could you try again, I now pushed the fix from Tobias on MAGEMin repo. I also tried your composition on my machine (On windows) and it works. Just to double check, which mode do you use here?

Closed system.

**Comment by CHNxzr** [comment] 2022-09-29 09:51
> in that case, can you give us more details on which parameters you exactly changed starting from the default parameters (all changes please).

ok!
![Uploading reply33.png…]()

**Comment by CHNxzr** [comment] 2022-09-29 09:51
![reply34](https://user-images.githubusercontent.com/114136385/193000500-906ad364-aa4b-44f1-b80c-37c0e353b0fc.png)
![reply35](https://user-images.githubusercontent.com/114136385/193000504-b4780480-c820-4ad2-aa66-3007768bc915.png)
![reply33](https://user-images.githubusercontent.com/114136385/193000587-a8d291c1-7fa5-4d50-babf-d46674b8d503.png)

**Comment by CHNxzr** [comment] 2022-09-29 09:55
Exactly I can receive the "_matlab_output" txt ,  it seems that there is just a wrong with printing.

**Comment by kellertobs** [comment] 2022-09-29 09:58
I just ran it again with your exact composition and P-T path and it runs through with no error.

**Comment by boriskaus** [comment] 2022-10-27 12:09
since we have no news on this, I'm closing the issue

**Closed by boriskaus** 2022-10-27 12:09 UTC
